 

 - name: win_ping module demo w01
   hosts: 127.0.0.1
   connection: local

   tasks:
   - name: Clean up
     shell: |
       ls /home/dago/ansible/

 - name: Test all hosts
   hosts: windows
   become: false
   gather_facts: false

   tasks:
   - name: test connection
     win_ping:

   - name: Obtain information about a registry key using short form
     win_reg_stat:
       path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion
     register: current_version



   - name: Create a directory if it does not exist
     ansible.builtin.file:
       path: /home/dago/ansible/storagedir1
       state: directory
       mode: '0755'
       owner: root
       group: root

#   - name: save output to /etc/ansible/backups
#     copy:
#       content: "{{ current_version.properties.CommonW6432Dir.type }}"
#       dest: "/home/dago/ansible/backupdictory/config_{{ inventory_hostname }}.txt"


#   - local_action: copy content="{{ current_version.properties.CommonW6432Dir.type }}" dest="/var/lib/awx/projects/storagedir/config_{{ inventory_hostname }}.txt"  
#   - local_action: copy content="{{ current_version.properties.CommonW6432Dir.type }}" dest="$HOME/projects/storagedir/config_{{ inventory_hostname }}.txt"  
   - local_action: copy content="{{ current_version.properties.CommonW6432Dir.type }}" dest="./storagedir1/config_{{ inventory_hostname }}.txt"  


   - name: Printing Something
     debug:
       msg: "{{ current_version.properties.CommonW6432Dir.type }}"


   - name: What is my inventory name
     debug:
       msg: 'Hola mundo: {{ testDagoVar }}'
#     debug: var={{ inventory_hostname }}   

################ ******************************* ###################

 - name: win_ping module demo win02
   hosts: windows02
   become: false
   gather_facts: false

   tasks:
   - name: copy file to dest
     win_copy:
       src: ./storagedir1/
       dest: C:\\Temp\\Installer\\


